version: '3.8'

networks:
  catalog-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local

services:
  catalogapi:
    image: catalog-cqrs-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=postgres;Port=5432;Database=CatalogDb;User Id=postgres;Password=postgres;
    depends_on:
      - postgres
    networks:
      - catalog-network

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogDb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - catalog-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - catalog-network

networks:
  catalog-network:
    driver: bridge

volumes:
  postgres-data:
